import { describe, it, expect } from 'vitest';
import { renderFixReport } from './report.js';
import type { FixReport, FixAttempt, AgentFinding } from '../types/index.js';

function makeFinding(overrides: Partial<AgentFinding> = {}): AgentFinding {
  return {
    id: 'F001',
    severity: 'HIGH',
    category: 'security',
    location: 'src/auth.ts:42',
    summary: 'SQL injection risk',
    detail: 'User input not sanitized',
    suggestion: 'Use parameterized queries',
    lenses: ['security'],
    ...overrides,
  };
}

function makeFix(overrides: Partial<FixAttempt> = {}): FixAttempt {
  return {
    findingId: 'F001',
    finding: makeFinding(),
    patch: '- old\n+ new',
    explanation: 'Applied parameterized query',
    status: 'verified',
    ...overrides,
  };
}

function makeReport(overrides: Partial<FixReport> = {}): FixReport {
  return {
    pr: { title: 'Fix auth', number: 99, repoOwner: 'owner', repoName: 'repo' },
    eligible: 2,
    generated: 2,
    verified: 1,
    reverted: 0,
    failed: 1,
    fixes: [],
    ...overrides,
  };
}

describe('renderFixReport', () => {
  it('renders header with PR info', () => {
    const output = renderFixReport(makeReport());
    expect(output).toContain('# AgentReview Fix Report: PR #99 — Fix auth');
    expect(output).toContain('owner/repo');
  });

  it('renders summary table with counts', () => {
    const output = renderFixReport(makeReport({ eligible: 5, generated: 4, verified: 3, reverted: 1, failed: 0 }));
    expect(output).toContain('| Findings eligible for fix | 5 |');
    expect(output).toContain('| Fixes generated | 4 |');
    expect(output).toContain('| Fixes verified | 3 |');
    expect(output).toContain('| Fixes reverted | 1 |');
    expect(output).toContain('| Fixes failed | 0 |');
  });

  it('renders verified fix with ✅ emoji', () => {
    const fix = makeFix({ status: 'verified' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('### ✅');
    expect(output).toContain('SQL injection risk');
  });

  it('renders failed fix with 💥 emoji', () => {
    const fix = makeFix({ status: 'failed' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('### 💥');
  });

  it('renders reverted fix with ❌ emoji', () => {
    const fix = makeFix({ status: 'reverted' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('### ❌');
  });

  it('renders applied fix with 🔧 emoji', () => {
    const fix = makeFix({ status: 'applied' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('### 🔧');
  });

  it('renders pending fix with ⏳ emoji', () => {
    const fix = makeFix({ status: 'pending' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('### ⏳');
  });

  it('shows clean message when no fixes', () => {
    const output = renderFixReport(makeReport({ fixes: [] }));
    expect(output).toContain('No Fixable Findings');
    expect(output).toContain('No findings were eligible for auto-fix');
  });

  it('renders multiple fixes in order', () => {
    const fix1 = makeFix({ findingId: 'F001', finding: makeFinding({ id: 'F001', summary: 'First issue' }), status: 'verified' });
    const fix2 = makeFix({ findingId: 'F002', finding: makeFinding({ id: 'F002', summary: 'Second issue' }), status: 'failed' });
    const output = renderFixReport(makeReport({ fixes: [fix1, fix2] }));
    const idx1 = output.indexOf('First issue');
    const idx2 = output.indexOf('Second issue');
    expect(idx1).toBeLessThan(idx2);
    expect(output).toContain('✅');
    expect(output).toContain('💥');
  });

  it('includes verification result when present', () => {
    const fix = makeFix({ verificationResult: 'Tests pass after fix' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('**Verification:** Tests pass after fix');
  });

  it('includes diff patch in code block', () => {
    const fix = makeFix({ patch: '- old line\n+ new line' });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('```diff');
    expect(output).toContain('- old line');
    expect(output).toContain('+ new line');
  });

  it('includes confidence score when present', () => {
    const fix = makeFix({ finding: makeFinding({ confidenceScore: 85 }) });
    const output = renderFixReport(makeReport({ fixes: [fix] }));
    expect(output).toContain('confidence: 85%');
  });

  it('includes footer with AgentReview link', () => {
    const output = renderFixReport(makeReport());
    expect(output).toContain('Generated by [AgentReview]');
  });
});
