import type { FixReport, FixAttempt } from '../types/index.js';

const STATUS_EMOJI: Record<string, string> = {
  verified: '✅',
  applied: '🔧',
  pending: '⏳',
  reverted: '❌',
  failed: '💥',
};

function renderFixEntry(fix: FixAttempt): string {
  const emoji = STATUS_EMOJI[fix.status] ?? '❓';
  const confidence = fix.finding.confidenceScore !== undefined
    ? ` _(confidence: ${fix.finding.confidenceScore}%)_`
    : '';

  const lines = [
    `### ${emoji} [${fix.findingId}] ${fix.finding.summary}`,
    `**Status:** ${fix.status}${confidence}`,
    `**Location:** \`${fix.finding.location}\``,
    `**Explanation:** ${fix.explanation}`,
  ];

  if (fix.verificationResult) {
    lines.push(`**Verification:** ${fix.verificationResult}`);
  }

  if (fix.patch) {
    lines.push('', '```diff', fix.patch, '```');
  }

  lines.push('', '---');
  return lines.join('\n');
}

export function renderFixReport(report: FixReport): string {
  const lines: string[] = [];

  lines.push(`# AgentReview Fix Report: PR #${report.pr.number} — ${report.pr.title}`);
  lines.push('');
  lines.push(`> **Repository:** ${report.pr.repoOwner}/${report.pr.repoName}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Findings eligible for fix | ${report.eligible} |`);
  lines.push(`| Fixes generated | ${report.generated} |`);
  lines.push(`| Fixes verified | ${report.verified} |`);
  lines.push(`| Fixes reverted | ${report.reverted} |`);
  lines.push(`| Fixes failed | ${report.failed} |`);
  lines.push('');

  if (report.fixes.length === 0) {
    lines.push('## No Fixable Findings');
    lines.push('');
    lines.push('No findings were eligible for auto-fix (only CRITICAL/HIGH/MEDIUM confirmed/uncertain findings qualify).');
  } else {
    lines.push('## Fixes');
    lines.push('');
    for (const fix of report.fixes) {
      lines.push(renderFixEntry(fix));
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [AgentReview](https://github.com/vidyasagarr7/agentreview)*');

  return lines.join('\n');
}
