import type { ConsolidatedReport, AgentFinding, FindingSeverity } from '../../types/index.js';

const SEVERITY_EMOJI: Record<FindingSeverity, string> = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🔵',
  INFO: '⚪',
};

const SEVERITY_LABEL: Record<FindingSeverity, string> = {
  CRITICAL: 'Must fix before merge',
  HIGH: 'Should fix before merge',
  MEDIUM: 'Consider fixing',
  LOW: 'Minor improvement',
  INFO: 'Informational',
};

const SEVERITY_ORDER: FindingSeverity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];

function renderFinding(f: AgentFinding): string {
  const lensTag = f.lenses.length > 1
    ? `[${f.lenses.join(' + ')}]`
    : `[${f.lenses[0] ?? 'unknown'}]`;

  return [
    `#### ${SEVERITY_EMOJI[f.severity]} ${lensTag} ${f.summary}`,
    ``,
    `**Location:** \`${f.location}\`  `,
    `**Category:** ${f.category}`,
    ``,
    f.detail,
    ``,
    `> **Suggestion:** ${f.suggestion}`,
    ``,
    `---`,
  ].join('\n');
}

function renderSummaryTable(report: ConsolidatedReport): string {
  const rows = SEVERITY_ORDER
    .filter((s) => report.stats.bySeverity[s] > 0)
    .map((s) => `| ${SEVERITY_EMOJI[s]} ${s} | ${report.stats.bySeverity[s]} | ${SEVERITY_LABEL[s]} |`);

  if (rows.length === 0) {
    return '| Severity | Count | Meaning |\n|----------|-------|------|\n| ✅ All clean | 0 | No issues found |';
  }

  return [
    '| Severity | Count | Meaning |',
    '|----------|-------|---------|',
    ...rows,
  ].join('\n');
}

export function renderMarkdown(report: ConsolidatedReport): string {
  const { pr, stats, findings, parseErrors, lensesRun, confidence, reviewedAt } = report;

  const lines: string[] = [];

  // Header
  lines.push(`<!-- agentreview -->`);
  lines.push(`# AgentReview: PR #${pr.number} — ${pr.title}`);
  lines.push(``);
  lines.push(`> **Reviewed by:** ${lensesRun.join(' · ')}  `);
  lines.push(`> **Reviewed at:** ${reviewedAt}  `);
  lines.push(`> **Files changed:** ${pr.filesChanged} | **+${pr.additions}** / **-${pr.deletions}** lines`);

  if (confidence === 'LOW') {
    lines.push(``);
    lines.push(`> ⚠️ **Review confidence: LOW** — one or more lenses failed or returned unparseable output. Results may be incomplete.`);
  }

  lines.push(``);
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(renderSummaryTable(report));

  // ParseErrors (shown prominently before findings)
  if (parseErrors.length > 0) {
    lines.push(``);
    lines.push(`## ⚠️ Parse Errors`);
    lines.push(``);
    lines.push(`The following lenses returned responses that could not be parsed. These results are **missing from the report** and the review may be incomplete:`);
    lines.push(``);
    for (const err of parseErrors) {
      lines.push(`### ⚠️ [PARSE ERROR] \`${err.lensId}\` lens`);
      lines.push(``);
      lines.push(`${err.message}`);
      lines.push(``);
      if (err.raw) {
        lines.push(`<details><summary>Raw response (truncated)</summary>`);
        lines.push(``);
        lines.push(`\`\`\``);
        lines.push(err.raw);
        lines.push(`\`\`\``);
        lines.push(`</details>`);
      }
      lines.push(``);
    }
  }

  // Findings grouped by severity
  if (findings.length > 0) {
    lines.push(`## Findings`);
    lines.push(``);

    for (const severity of SEVERITY_ORDER) {
      const severityFindings = findings.filter((f) => f.severity === severity);
      if (severityFindings.length === 0) continue;

      lines.push(`### ${SEVERITY_EMOJI[severity]} ${severity} (${severityFindings.length})`);
      lines.push(``);

      for (const f of severityFindings) {
        lines.push(renderFinding(f));
        lines.push(``);
      }
    }
  } else if (parseErrors.length === 0) {
    lines.push(``);
    lines.push(`## ✅ No Issues Found`);
    lines.push(``);
    lines.push(`All lenses reviewed this PR and found no issues. Ship it! 🚀`);
  }

  // Lens Notes
  lines.push(`## Lens Notes`);
  lines.push(``);

  for (const lensId of lensesRun) {
    const count = stats.byLens[lensId] ?? 0;
    const isClean = stats.cleanLenses.includes(lensId);
    const isErrored = stats.erroredLenses.includes(lensId);
    const isParseError = stats.parseErrorLenses.includes(lensId);

    lines.push(`### ${lensId}`);

    if (isErrored) {
      lines.push(`❌ This lens encountered an error and could not complete the review.`);
    } else if (isParseError) {
      lines.push(`⚠️ This lens returned a response that could not be parsed.`);
    } else if (isClean) {
      lines.push(`✅ No issues found.`);
    } else {
      lines.push(`Found ${count} issue${count !== 1 ? 's' : ''}.`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by [AgentReview](https://github.com/agentreview/agentreview)*`);

  return lines.join('\n');
}
